project:
  type: website
  output-dir: docs

website:
  title: "HSBC Java Camp by Laboratoria"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "M贸dulo 1"
        href: Modulo_1_Java_Basics.md
      - text: "M贸dulo 2"
        href: Modulo_2_Deeper_Java.md
      - text: "M贸dulo 3"
        href: Modulo_3_Java_Craft.md
      - text: "M贸dulo 4"
        href: Modulo_4_AdvancedPrep.md

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    lang: es

margin-header: |
  ![](/images/logo_negro.png)
