project:
  type: website
  output-dir: docs

website:
  title: "HSBC Java Camp by Laboratoria"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Módulo 1"
        href: Modulo_1_Java_Basics.md
      - text: "Módulo 2"
        href: Modulo_2_Deeper_Java.md

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    lang: es

margin-header: |
  ![](/images/logo_negro.png)
