project:
  type: website
  output-dir: docs

website:
  title: "HSBC Java Camp by Laboratoria"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "M贸dulo 1"
        href: Modulo_1_Beginner.md
      - text: "M贸dulo 2"
        href: Modulo_2_Intermediate.md
      - text: "M贸dulo 3"
        href: Modulo_3_Advanced.md
      - text: "M贸dulo 4"
        href: Modulo_4_AdvancedPrep.md
      - text: "Referencias"
        href: References.md

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    lang: es

margin-header: |
  ![](/images/logo_negro.png)
