project:
  type: website

website:
  title: "Java Coding Challenges"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Weeks 1-2"
        href: Week1-2_Beginner.md
      - text: "Weeks 3-4"
        href: Week3-4_Intermediate.md
      - text: "Weeks 5-6"
        href: Week5-6_Advanced.md
      - text: "Weeks 7-8"
        href: Week7-8_AdvancedPrep.md

format:
  html:
    theme: default